### ISSUE TITLE
How do I read the confusion matrix from validate.cross().metrics()

### ISSUE THREAD

**Issue by jtara1** [winkjs/wink-helpers#17]
I had another question about the output from metrics() function inside of helpers.validate.cross( labels ) 

Are the confusion matrix properties the predicted label or the actual label?

output is something like:

```
{ 
    spam: { spam: 50, notSpam: 2 }, 
    notSpam: { spam: 1, notSpam: 90 } 
}
```

how would this data fit into this matrix?

```
[ [ TP, FP ],
  [ FN, TN ] ]
``` 

edit: I'm guessing it's 

```
[ [ 50, 2 ],
  [ 1, 90 ] ]
```

which also means the properties are the actual label

**Comment by rachnachakraborty** [comment]
Hi @jtara1,

You are right… the matrix maps as you have highlighted above.

About your other clarification on cross-validation: it typically involves shuffling, partitioning, training and evaluation. The `wink-helpers` provide mechanisms for **shuffling** and **comprehensive evaluation**, whereas partitioning can be easily accomplished by standard javascript.

Best,
Rachna
